<<<<<<< HEAD
{"testCaseId":"C:\\Users\\harit\\git\\UTM-Go-Katalon-Testing\\Test Cases\\Facility Module\\Submit complaint fails, missing required fields.tc","driverType":"CHROME_DRIVER","withProfile":false,"recordingConnectionId":"","customCapabilityName":"","startupUrl":"https://utm-go.vercel.app/","recordingType":"NEW_BROWSER"}
=======
{"testCaseId":"C:\\Users\\fakhr\\git\\UTM-Go-Katalon-Testing\\Test Cases\\Successful Activity Registration.tc","driverType":"CHROME_DRIVER","withProfile":false,"recordingConnectionId":"","customCapabilityName":"","startupUrl":"https://utm-go.vercel.app/","recordingType":"NEW_BROWSER"}
>>>>>>> branch 'main' of https://github.com/epulonzo/UTM-Go-Katalon-Testing.git
