<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>svg_lucide lucide-book</name>
   <tag></tag>
   <elementGuidId>8547f991-8600-4e43-9b0f-67ead53e4f30</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' h-full ') and contains(concat(' ', normalize-space(@class), ' '), ' flex-col ') and contains(concat(' ', normalize-space(@class), ' '), ' justify-center ') and (position() = 3)]//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' lucide-book ')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>.h-full.flex-col.justify-center:nth-child(3) .lucide-book</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Book&quot;s]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>svg</value>
      <webElementGuid>71aa6961-842f-419b-ab4b-ccac02ed6329</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xmlns</name>
      <type>Main</type>
      <value>http://www.w3.org/2000/svg</value>
      <webElementGuid>d4621f92-a7ef-441f-acb2-f3631f958f81</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>20</value>
      <webElementGuid>a2d95293-8232-4411-b8b3-11549cf539e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>20</value>
      <webElementGuid>af67e08f-414e-4a09-ae03-c624f314aa85</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>viewBox</name>
      <type>Main</type>
      <value>0 0 24 24</value>
      <webElementGuid>27210aaa-047f-4c67-91a7-7d0b1826c2be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>fill</name>
      <type>Main</type>
      <value>none</value>
      <webElementGuid>d95dcf18-064d-4956-a6d8-e36780bb5ea9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>stroke</name>
      <type>Main</type>
      <value>currentColor</value>
      <webElementGuid>5985dd91-b4c2-4358-86d3-c6a30dcb1f95</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>stroke-width</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>43378340-1b69-4f94-9a5c-c921855b70bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>stroke-linecap</name>
      <type>Main</type>
      <value>round</value>
      <webElementGuid>fd6cb087-7d59-42ac-824f-0288f060b479</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>stroke-linejoin</name>
      <type>Main</type>
      <value>round</value>
      <webElementGuid>35bfc6a3-07ac-482e-8af1-e07920f3d9d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>lucide lucide-book</value>
      <webElementGuid>a8a1fc44-d38b-46c2-812f-7c6733ff26bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>bb420636-04bf-452b-9579-de2f593dda5f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-87825c451bdbf7c0831d704a8b838cf7</value>
      <webElementGuid>e4f874c3-a8e2-4e73-9af9-b8f19c56d15e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' h-full ') and contains(concat(' ', normalize-space(@class), ' '), ' flex-col ') and contains(concat(' ', normalize-space(@class), ' '), ' justify-center ') and (position() = 3)]//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' lucide-book ')]</value>
      <webElementGuid>fdb7c86e-0ba5-40a8-a10f-2594c8149bda</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' h-full ') and contains(concat(' ', normalize-space(@class), ' '), ' flex-col ') and contains(concat(' ', normalize-space(@class), ' '), ' justify-center ') and (position() = 3)]//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' lucide-book ')]</value>
      <webElementGuid>128ec19e-8456-49fc-91c7-9905dc4d5b3b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
